# fly.toml app configuration file generated for weekendfollowups on 2025-01-22T13:53:35+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weekendfollowups'
primary_region = 'sjc'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
